// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TruSite.Api.Data;

namespace TruSite.Api.Migrations
{
    [DbContext(typeof(TruSiteContext))]
    [Migration("20181112225352_DbInit")]
    partial class DbInit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TruSite.Api.Models.DataModels.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Attention");

                    b.Property<string>("City");

                    b.Property<Guid>("ContactId");

                    b.Property<string>("Name");

                    b.Property<string>("PostalCode");

                    b.Property<bool>("Primary");

                    b.Property<string>("State");

                    b.Property<string>("StreetOne");

                    b.Property<string>("StreetTwo");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("TruSite.Api.Models.DataModels.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("Description");

                    b.Property<Guid>("EntityId");

                    b.Property<int>("EntityType");

                    b.Property<string>("Name");

                    b.Property<bool>("Primary");

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("TruSite.Api.Models.DataModels.InventoryFinal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CountDateTime");

                    b.Property<Guid>("ItemId");

                    b.Property<int>("Quantity");

                    b.HasKey("Id");

                    b.ToTable("InventoryFinals");
                });

            modelBuilder.Entity("TruSite.Api.Models.DataModels.InventorySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Count");

                    b.Property<DateTime>("CountDateTime");

                    b.Property<Guid>("ItemId");

                    b.Property<int>("Quantity");

                    b.Property<DateTime>("SnapshotDateTime");

                    b.HasKey("Id");

                    b.ToTable("InventorySnapshots");
                });

            modelBuilder.Entity("TruSite.Api.Models.DataModels.InventoryTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ItemId");

                    b.Property<int>("Quantity");

                    b.Property<DateTime>("TransactionDateTime");

                    b.Property<int>("TransactionType");

                    b.HasKey("Id");

                    b.ToTable("InventoryTransactions");
                });

            modelBuilder.Entity("TruSite.Api.Models.DataModels.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("BillingAddressId");

                    b.Property<Guid>("ClientId");

                    b.Property<Guid>("DeliveryAddressId");

                    b.Property<decimal>("Fees");

                    b.Property<DateTime>("InvoiceDate");

                    b.Property<string>("InvoiceNumber");

                    b.Property<decimal>("PaidAmount");

                    b.Property<bool>("PaidInFull");

                    b.Property<decimal>("Shipping");

                    b.Property<decimal>("Taxes");

                    b.HasKey("Id");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("TruSite.Api.Models.DataModels.InvoiceDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("InvoiceId");

                    b.Property<Guid>("ItemDetailId");

                    b.Property<Guid>("ItemPriceId");

                    b.Property<int>("Quantity");

                    b.Property<decimal>("UnitPrice");

                    b.HasKey("Id");

                    b.ToTable("InvoiceDetails");
                });

            modelBuilder.Entity("TruSite.Api.Models.DataModels.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("TruSite.Api.Models.DataModels.ItemDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BeginDate");

                    b.Property<int>("CaseQuantity");

                    b.Property<string>("Description");

                    b.Property<DateTime>("EndDate");

                    b.Property<Guid>("ItemId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("ItemDetails");
                });

            modelBuilder.Entity("TruSite.Api.Models.DataModels.ItemImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BeginDate");

                    b.Property<DateTime>("EndDate");

                    b.Property<byte[]>("Image");

                    b.Property<Guid>("ItemDetailId");

                    b.Property<int>("Ordinal");

                    b.HasKey("Id");

                    b.ToTable("ItemImages");
                });

            modelBuilder.Entity("TruSite.Api.Models.DataModels.ItemPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BeginDate");

                    b.Property<decimal>("CasePrice");

                    b.Property<DateTime>("EndDate");

                    b.Property<Guid>("ItemId");

                    b.Property<decimal>("Price");

                    b.Property<decimal>("SalePrice");

                    b.HasKey("Id");

                    b.ToTable("ItemPrices");
                });

            modelBuilder.Entity("TruSite.Api.Models.DataModels.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDateTime");

                    b.Property<Guid>("ObjectId");

                    b.Property<int>("ObjectType");

                    b.Property<bool>("Private");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("TruSite.Api.Models.DataModels.Phone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<Guid>("ContactId");

                    b.Property<int>("Extension");

                    b.Property<string>("Name");

                    b.Property<long>("Number");

                    b.Property<int>("PhoneType");

                    b.Property<bool>("Primary");

                    b.HasKey("Id");

                    b.ToTable("PhoneNumbers");
                });

            modelBuilder.Entity("TruSite.Api.Models.DataModels.PurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AddressId");

                    b.Property<decimal>("Fees");

                    b.Property<DateTime>("OrderDate");

                    b.Property<DateTime>("ResolveDate");

                    b.Property<decimal>("ShippingCost");

                    b.Property<int>("State");

                    b.Property<decimal>("Taxes");

                    b.Property<Guid>("VendorId");

                    b.HasKey("Id");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("TruSite.Api.Models.DataModels.PurchaseOrderDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ItemId");

                    b.Property<Guid>("PurchaseOrderId");

                    b.Property<int>("Quantity");

                    b.Property<int>("State");

                    b.Property<decimal>("UnitCost");

                    b.HasKey("Id");

                    b.ToTable("PurchaseOrderDetails");
                });

            modelBuilder.Entity("TruSite.Api.Models.DataModels.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("VendorNumber");

                    b.HasKey("Id");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("TruSite.Api.Models.DataModels.Vendor_Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ItemId");

                    b.Property<Guid>("VendorId");

                    b.Property<string>("VendorItemNumber");

                    b.HasKey("Id");

                    b.ToTable("VendorItems");
                });

            modelBuilder.Entity("TruSite.Api.Models.DataModels.WebAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<Guid>("ContactId");

                    b.Property<string>("Name");

                    b.Property<bool>("Primary");

                    b.Property<string>("SiteAddress");

                    b.HasKey("Id");

                    b.ToTable("WebAddresses");
                });
#pragma warning restore 612, 618
        }
    }
}
